# Generated by Django 2.1.5 on 2019-05-16 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specode', models.CharField(default='', max_length=100)),
                ('recdate', models.DateField(default=datetime.date.today)),
                ('duedate', models.DateField(default=datetime.date.today)),
                ('textf1', models.CharField(default='', max_length=100)),
                ('textf2', models.CharField(default='', max_length=100)),
                ('textf3', models.CharField(default='', max_length=100)),
                ('textf4', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, ''), (1, 'İcra O.')], default=0)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
            ],
        ),
    ]
