# Generated by Django 2.1.5 on 2019-05-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrecord',
            options={'verbose_name': 'Event Record'},
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='technology',
        ),
    ]
