# Generated by Django 2.1.5 on 2019-05-16 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0002_auto_20190516_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='duedate',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Due-Date'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='recdate',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='specode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, ''), (1, 'İcra O.')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='textf1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Object Name'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='textf2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Task Title'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='textf3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Task Started By'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='textf4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Task Executor'),
        ),
    ]
