# Generated by Django 2.1.5 on 2019-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0003_auto_20190516_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Code')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'İcra O.')], default=0, verbose_name='Status'),
        ),
    ]
