# Generated by Django 2.1.5 on 2019-05-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0004_auto_20190516_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event Type'},
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='specode',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.DO_NOTHING, to='eventhandler.EventType'),
        ),
    ]
