# Generated by Django 2.1.5 on 2019-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0007_auto_20190516_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='specode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type'),
        ),
    ]
