# Generated by Django 2.1.5 on 2019-05-24 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0008_auto_20190516_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrecord',
            options={'verbose_name': 'Event Record', 'verbose_name_plural': 'Event Records'},
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='duedate',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='textf3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Task From'),
        ),
    ]
